name: Create GitHub Page

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2

    - name: Install Deps (Screw you npm install)
      run: npm ci

    - name: Build the html
      run: npm run build
    - uses: actions/delete-package-versions@v1
      with: 
        num-old-versions-to-delete: 10
        token: ${{ secrets.GITHUB_TOKEN }}

    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
      env:
        CI: true